import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface ProjectFormat {
  isTypeScript: boolean;
  isESM: boolean;
}

// TypeScript detection: a tsconfig.json in cwd. Module-system detection
// (ESM vs CommonJS) only matters for the JavaScript case -- TypeScript
// source always uses import/export syntax regardless of what a
// project's own tsconfig compiles it to. Read from package.json's own
// "type" field, the same TS/ESM/CJS duality already documented as real,
// live tech debt for packages/sdk itself (CLAUDE.md's Known Technical
// Debt section); getting it wrong here would hand a brand-new developer
// a file that doesn't run. See docs/architecture/cli-init-design.md
// section 8.
export function detectProjectFormat(cwd: string): ProjectFormat {
  const isTypeScript = existsSync(join(cwd, "tsconfig.json"));
  const isESM = readPackageJsonType(cwd) === "module";
  return { isTypeScript, isESM };
}

function readPackageJsonType(cwd: string): string | null {
  try {
    const parsed: unknown = JSON.parse(
      readFileSync(join(cwd, "package.json"), "utf8"),
    );
    if (typeof parsed !== "object" || parsed === null) return null;
    const type = (parsed as Record<string, unknown>).type;
    return typeof type === "string" ? type : null;
  } catch {
    return null;
  }
}

export interface ScaffoldFile {
  fileName: string;
  content: string;
}

// Both files land at the project root, next to .env, never guessed
// into a src/ or other conventional source directory: a root-level
// file is the one location init can place something without having to
// guess how a given project organizes its own source.
export function scaffoldFiles(format: ProjectFormat): ScaffoldFile[] {
  const ext = format.isTypeScript ? "ts" : "js";
  return [
    { fileName: `agenttrace.${ext}`, content: clientFileContent(format) },
    {
      fileName: `agenttrace.example.${ext}`,
      content: exampleFileContent(format),
    },
  ];
}

// Loads .env itself, via dotenv, rather than assuming the environment
// already has these two variables set: found live during M17's own
// verification that plain `node agenttrace.example.js` never loads
// .env on its own (that's a framework convenience, e.g. Next.js, not
// Node behavior), so the exact "run this to try it now" step this
// project's own next-steps text recommends would otherwise crash.
// Matches apps/reference-agent's own existing dotenv usage, not a new
// pattern. `init` installs `dotenv` alongside the SDK for this reason.
function clientFileContent(format: ProjectFormat): string {
  if (format.isTypeScript) {
    return `import { config } from "dotenv";
import { AgentTraceClient } from "@agenttraceai/sdk";

config();

export const agenttrace = new AgentTraceClient({
  apiKey: process.env.AGENTTRACE_API_KEY!,
  baseUrl: process.env.AGENTTRACE_BASE_URL!,
});
`;
  }
  if (format.isESM) {
    return `import { config } from "dotenv";
import { AgentTraceClient } from "@agenttraceai/sdk";

config();

export const agenttrace = new AgentTraceClient({
  apiKey: process.env.AGENTTRACE_API_KEY,
  baseUrl: process.env.AGENTTRACE_BASE_URL,
});
`;
  }
  return `require("dotenv").config();
const { AgentTraceClient } = require("@agenttraceai/sdk");

const agenttrace = new AgentTraceClient({
  apiKey: process.env.AGENTTRACE_API_KEY,
  baseUrl: process.env.AGENTTRACE_BASE_URL,
});

module.exports = { agenttrace };
`;
}

function exampleFileContent(format: ProjectFormat): string {
  // TypeScript's own module resolution tolerates an extensionless
  // relative specifier here, but real Node ESM resolution does not:
  // found live (a real ERR_MODULE_NOT_FOUND) during M17's own
  // verification, running the generated example in a real "type":
  // "module" project. CommonJS's `require()` is the odd one out,
  // trying multiple extensions automatically, which is why it alone
  // doesn't need one.
  const importLine = format.isTypeScript
    ? `import { agenttrace } from "./agenttrace";`
    : format.isESM
      ? `import { agenttrace } from "./agenttrace.js";`
      : `const { agenttrace } = require("./agenttrace");`;

  return `// Example usage of the AgentTrace SDK, generated by \`agenttrace init\`.
// Copy what you need into your own code -- this file is never imported
// by anything AgentTrace generates, and is safe to delete once you've
// wired up your own instrumentation.
${importLine}

async function example() {
  await agenttrace.trace(
    { name: "example-agent-run", agentName: "my-agent" },
    async (trace) => {
      const result = await trace.span(
        { name: "example-step", type: "CUSTOM" },
        async () => {
          // Replace this with a real step in your agent (an LLM call,
          // a tool call, a retrieval lookup).
          return "hello from agenttrace";
        },
      );

      trace.setOutput(result);
    },
  );
}

example();
`;
}

// Skip-by-default, not overwrite-by-default: a scaffold file that
// already exists means someone already made whatever choice was in it,
// and silently regenerating it risks clobbering real edits. `force` is
// the one explicit way to regenerate both files anyway. See
// docs/architecture/cli-init-design.md section 9.
export interface WriteScaffoldResult {
  written: string[];
  skipped: string[];
}

export function writeScaffoldFiles(
  cwd: string,
  format: ProjectFormat,
  force: boolean,
): WriteScaffoldResult {
  const result: WriteScaffoldResult = { written: [], skipped: [] };
  for (const file of scaffoldFiles(format)) {
    const filePath = join(cwd, file.fileName);
    if (existsSync(filePath) && !force) {
      result.skipped.push(file.fileName);
      continue;
    }
    writeFileSync(filePath, file.content);
    result.written.push(file.fileName);
  }
  return result;
}

// The exact command to suggest for running the generated example
// directly, matching the file extension/format init just chose.
export function runExampleCommand(format: ProjectFormat): string {
  const exampleFile = `agenttrace.example.${format.isTypeScript ? "ts" : "js"}`;
  return format.isTypeScript ? `npx tsx ${exampleFile}` : `node ${exampleFile}`;
}
